/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PwcChatList {}
}

declare global {


  interface HTMLPwcChatListElement extends Components.PwcChatList, HTMLStencilElement {}
  var HTMLPwcChatListElement: {
    prototype: HTMLPwcChatListElement;
    new (): HTMLPwcChatListElement;
  };
  interface HTMLElementTagNameMap {
    'pwc-chat-list': HTMLPwcChatListElement;
  }
}

declare namespace LocalJSX {
  interface PwcChatList {}

  interface IntrinsicElements {
    'pwc-chat-list': PwcChatList;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pwc-chat-list': LocalJSX.PwcChatList & JSXBase.HTMLAttributes<HTMLPwcChatListElement>;
    }
  }
}


